language: bash
services: docker
install: false
script:
- docker build -t rjshrjndrn/ansible:2.4.1 .
- docker run -d -p 8000:8000 rjshrjndrn/ansible:2.4.1
- docker ps
- bash -x test.sh
after_script:
- docker images
